#docker-compose-pomodoro.yml sans DB

version: '3.9'
services:
  pomodoro:
    build: .
    container_name: pomodoro
    networks:
      - shared-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pomodoro.rule=Host(`pomodoro.manifesto-app.fr`)"
      - "traefik.http.services.pomodoro.loadbalancer.server.port=3000"
      - "traefik.http.routers.pomodoro.entrypoints=websecure"
      - "traefik.http.routers.pomodoro.tls.certresolver=myresolver"
      - "traefik.http.middlewares.pomodoro-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pomodoro-http.rule=Host(`pomodoro.manifesto-app.fr`)"
      - "traefik.http.routers.pomodoro-http.entrypoints=web"
      - "traefik.http.routers.pomodoro-http.middlewares=pomodoro-redirect"
networks:
  shared-network:
    external: true