#docker-compose-pomodoro.yml sans DB

  version: '3.9'

  services:
    pomodoro:
      build: .
      container_name: pomodoro
      ports:
        - "3008:3000"
      networks:
        - web
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.Pomodoro.rule=PathPrefix(`/Pomodoro`)"
        - "traefik.http.services.Pomodoro.loadbalancer.server.port=3000"
        - "traefik.http.routers.Pomodoro.entrypoints=web"

  networks:
    web:
      external: true